require('editor.icons')
require('editor.move')
require('editor.colorscheme')
require('editor.pick')
require('editor.files')
-- require('editor.notify')
require('editor.pairs')
require('editor.indentmini')
require('editor.lualine')
require('editor.noice')
